project:
  type: website
  preview:
    port: 5555

website:
  title: "R Primers"
  bread-crumbs: false
  
  repo-url: "https://github.com/andrewheiss/r-primers"
  repo-actions: [edit, issue]

  navbar:
    pinned: true
    left:
      - about.qmd
    right:
      - icon: github
        aria-label: github
        href: https://github.com/andrewheiss/r-primers
  
  sidebar: 
    style: "docked"
    collapse-level: 2
    contents: 
      - section: "The basics"
        contents:
          - section: "Data visualization basics"
            contents:
              - basics/01-visualization-basics/index.qmd
              - basics/01-visualization-basics/01-code-template.qmd
              - basics/01-visualization-basics/02-aesthetic-mappings.qmd
              - basics/01-visualization-basics/03-geometric-objects.qmd
              - basics/01-visualization-basics/04-ggplot2-package.qmd
          - section: "Programming basics"
            contents:
              - basics/02-programming-basics/index.qmd
              - basics/02-programming-basics/01-functions.qmd
              - basics/02-programming-basics/02-arguments.qmd
              - basics/02-programming-basics/03-objects.qmd
              - basics/02-programming-basics/04-vectors.qmd
              - basics/02-programming-basics/05-types.qmd
              - basics/02-programming-basics/06-lists.qmd
              - basics/02-programming-basics/07-packages.qmd

      - section: "Work with data"
        contents:
          - section: "Working with tibbles"
            contents:
              - transform-data/01-tibbles/index.qmd
              - transform-data/01-tibbles/01-babynames.qmd
              - transform-data/01-tibbles/02-tibbles.qmd
              - transform-data/01-tibbles/03-tidyverse.qmd
          - section: "Isolating data with {dplyr}"
            contents:
              - transform-data/02-isolating/index.qmd
              - transform-data/02-isolating/01-your-name.qmd
              - transform-data/02-isolating/02-select.qmd
              - transform-data/02-isolating/03-filter.qmd
              - transform-data/02-isolating/04-arrange.qmd
              - transform-data/02-isolating/05-pipe.qmd
          - section: "Deriving information with {dplyr}"
            contents:
              - transform-data/03-deriving/index.qmd
              - transform-data/03-deriving/01-most-popular-names.qmd
              - transform-data/03-deriving/02-summarize.qmd
              - transform-data/03-deriving/03-group_by.qmd
              - transform-data/03-deriving/04-mutate.qmd
              - transform-data/03-deriving/05-challenges.qmd

format:
  html:
    theme: 
      - zephyr
      - html/custom.scss
    toc: true
    toc-depth: 3
    knitr:
      opts_chunk:
        dev: "ragg_png"
        dpi: 300
