project:
  type: website
  preview:
    port: 5555

website:
  title: "R Primers"
  bread-crumbs: false

  navbar:
    pinned: true
    left:
      - about.qmd
  
  sidebar: 
    style: "docked"
    collapse-level: 2
    contents: 
      - section: "The basics"
        contents:
          - section: "Data visualization basics"
            contents:
              - basics/01-visualization-basics/index.qmd
              - basics/01-visualization-basics/01-code-template.qmd
              - basics/01-visualization-basics/02-aesthetic-mappings.qmd
              - basics/01-visualization-basics/03-geometric-objects.qmd
              - basics/01-visualization-basics/04-ggplot2-package.qmd
          - section: "Programming basics"
            contents:
              - basics/02-programming-basics/index.qmd
              - basics/02-programming-basics/01-functions.qmd
              - basics/02-programming-basics/02-arguments.qmd
              - basics/02-programming-basics/03-objects.qmd
              - basics/02-programming-basics/04-vectors.qmd
              - basics/02-programming-basics/05-types.qmd
              - basics/02-programming-basics/06-lists.qmd
              - basics/02-programming-basics/07-packages.qmd
      - section: "Work with data"
        contents:
          - section: "Working with tibbles"
            contents:
              - text: "Welcome"
              - text: "Blah"
              - text: "Blah"
          - section: "Isolating data with {dplyr}"
            contents:
              - text: "Welcome"
              - text: "Blah"
              - text: "Blah"
          - section: "Deriving information with {dplyr}"
            contents:
              - text: "Welcome"
              - text: "Blah"
              - text: "Blah"

format:
  html:
    theme: 
      - zephyr
      - html/custom.scss
    toc: true
    toc-depth: 3
    knitr:
      opts_chunk:
        dev: "ragg_png"
        dpi: 300
